#------------------------------------------------------------------------------
# written by: mcdaniel
# date: june-2022
#
# usage: top-level workflow. Initiated manually from Github Actions console page
#        Builds all Docker containers.
#------------------------------------------------------------------------------
name: Build Optional Containers

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ENABLE_BACKUP: true
      ENABLE_CREDENTIALS: false
      ENABLE_MFE: true

      SUBDOMAIN: {{ cookiecutter.environment_subdomain }}
      DOMAIN_NAME: {{ cookiecutter.global_root_domain }}
      SITE_NAME: {{ cookiecutter.global_platform_name }}
      AWS_REGION: {{ cookiecutter.global_aws_region }}

    steps:
      - uses: actions/checkout@v3.0.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.6.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Build Backup
        if: ${{ env.ENABLE_BACKUP == 'true' }}
        uses: openedx-actions/tutor-plugin-build-backup@v0.1.3

      - name: Build Credentials
        if: ${{ env.ENABLE_CREDENTIALS == 'true' }}
        uses: openedx-actions/tutor-plugin-build-credentials@v0.1.2

      - name: Build MFE
        if: ${{ env.ENABLE_MFE == 'true' }}
        uses: openedx-actions/tutor-plugin-build-mfe@v0.1.2
        with:
          subdomain: ${SUBDOMAIN}
          domain-name: ${DOMAIN_NAME}
          site-name: ${SITE_NAME}
