#------------------------------------------------------------------------------
# written by: Miguel Afonso
#             https://www.linkedin.com/in/mmafonso/
#
# date: Aug-2021
#
# usage: Creates a Tutor Docker image using the latest stable version of Open edX.
#        additionally installs
#        - custom theme
#        - plugin
#        - various Xblocks
#        Registers the new container in AWS ECR.
#------------------------------------------------------------------------------
name: Build openedx Image

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ECR_REPOSITORY: openedx
      ECR_REGISTRY: {{ cookiecutter.global_account_id }}.dkr.ecr.{{ cookiecutter.global_aws_region }}.amazonaws.com
    steps:
      - uses: actions/checkout@v3.0.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.6.1
        with:
          aws-access-key-id: {% raw %}${{ secrets.AWS_ACCESS_KEY_ID }}{% endraw %}
          aws-secret-access-key: {% raw %}${{ secrets.AWS_SECRET_ACCESS_KEY }}{% endraw %}
          aws-region: {{ cookiecutter.global_aws_region }}

      - name: Build the image and upload to AWS ECR
        uses: openedx-actions/tutor-plugin-build-openedx@v0.1.8
        with:
          custom-theme-repository: '{{ cookiecutter.ci_build_theme_repository }}'
          custom-theme-repository-ref: '{{ cookiecutter.ci_build_theme_ref }}'

          custom-plugin-repository: '{{ cookiecutter.ci_build_plugin_repository }}'
          custom-plugin-repository-organization: '{{ cookiecutter.ci_build_plugin_org }}'
          custom-plugin-repository-ref: '{{ cookiecutter.ci_build_plugin_ref }}'

          custom-xblock-repository: '{{ cookiecutter.ci_build_xblock_repository }}'
          custom-xblock-repository-organization: '{{ cookiecutter.ci_build_xblock_org }}'
          custom-xblock-repository-ref: '{{ cookiecutter.ci_build_xblock_ref }}'
