edx:
    cybersource:
        access_key: SET-ME-PLEASE
        apple_pay_country_code: US
        apple_pay_merchant_id_certificate_path: /edx/etc/ssl/apple_pay_merchant.pem
        apple_pay_merchant_id_domain_association: 'This value should also be in
            private configuration. It, too,

            will span multiple lines.

            '
        apple_pay_merchant_identifier: merchant.com.example
        cancel_page_url: /checkout/cancel-checkout/
        merchant_id: SET-ME-PLEASE
        payment_page_url: https://testsecureacceptance.cybersource.com/pay
        profile_id: SET-ME-PLEASE
        receipt_page_url: /checkout/receipt/
        secret_key: SET-ME-PLEASE
        send_level_2_3_details: true
        soap_api_url: https://ics2wstest.ic3.com/commerce/1.x/transactionProcessor/CyberSourceTransaction_1.140.wsdl
        sop_access_key: SET-ME-PLEASE
        sop_payment_page_url: https://testsecureacceptance.cybersource.com/silent/pay
        sop_profile_id: SET-ME-PLEASE
        sop_secret_key: SET-ME-PLEASE
        transaction_key: SET-ME-PLEASE
    paypal:
        mode: sandbox
        client_id: SET-ME-PLEASE
        client_secret: SET-ME-PLEASE
        cancel_checkout_path: /checkout/cancel-checkout/
        error_url: /checkout/error/
        receipt_url: /checkout/receipt/
    stripe:
        publishable_key: SET-ME-PLEASE
        secret_key: SET-ME-PLEASE
        country: US
        apple_pay_country_code: US
        apple_pay_merchant_id_certificate_path: /edx/etc/ssl/apple_pay_merchant.pem
        apple_pay_merchant_id_domain_association: 'This value should also be in
            private configuration. It, too,
            will span multiple lines.
            '
        apple_pay_merchant_identifier: merchant.com.example
