apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: vpa-recommender-prometheus-grafana
  namespace: monitoring
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       prometheus-grafana
  updatePolicy:
    updateMode: "Auto"
