apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: vpa-recommender-cert-manager-cainjector
  namespace: vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       cert-manager-cainjector
  updatePolicy:
    updateMode: "Auto"
