LMS_HOSTNAME={{ cookiecutter.prod_environment }}.{{ cookiecutter.global_root_domain }}
CMS_HOSTNAME=studio.{{ cookiecutter.prod_environment }}.{{ cookiecutter.global_root_domain }}
DOCKER_IMAGE_OPENEDX=320713933456.dkr.ecr.{{ cookiecutter.global_aws_region }}.amazonaws.com/openedx:latest
