#------------------------------------------------------------------------------
# written by: Miguel Afonso
#             https://www.linkedin.com/in/mmafonso/
#
# date: Aug-2021
#
# usage: setup SSL certs for EKS load balancer worker node instances.
#        see https://cert-manager.io/docs/
#------------------------------------------------------------------------------
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: le-crt
spec:
  secretName: wild-hosting-live-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  commonName: {{ cookiecutter.global_admin_subdomain }}.{{ cookiecutter.global_root_domain }}
  dnsNames:
    - "*.{{ cookiecutter.global_admin_subdomain }}.{{ cookiecutter.global_root_domain }}"
