#------------------------------------------------------------------------------ 
# written by: Miguel Afonso
#             https://www.linkedin.com/in/mmafonso/
#
# date: Aug-2021
#
# usage: setup SSL certs for EKS load balancer worker node instances.
#------------------------------------------------------------------------------ 
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: no-reply@stepwisemath.ai
    privateKeySecretRef:
      name: letsencrypt
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
          route53:
            region: us-east-2
            hostedZoneID: Z0232691KVI7Y7U23HBD

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: le-crt
spec:
  secretName: wild-openedx-prod-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  commonName: web.stepwisemath.ai
  dnsNames:
    - "*.web.stepwisemath.ai"
